/* ============================================================================
   cat-translator :: lexicon.js        *** GENERATED by tools/make-lexicon.mjs ***

   English -> Meownese. Do not hand-edit; run `node tools/make-lexicon.mjs`, which
   re-designs the codebook against measured acoustics and rewrites this file.

   A token = onset-vowel-tone-length
      onset  : none | m | prr | h
      vowel  : a e i o u y
      tone   : flat | rise | fall | arch | dip     (semantics: fall = no/bad,
      length : short | normal | long                rise = question/urgency)

   Every line is one SYNONYM GROUP: the first word is what the decoder answers.
   Every meaning owns a distinct meow, picked so the ~120 sounds sit as far
   apart as possible in measured acoustic space (tools/make-lexicon.mjs), while
   keeping the tone and length of the original hand-written meow. Numbers are
   counted out as repeats of a single counting meow - cute, and an extra or
   missing meow only shifts the number instead of corrupting the sentence.
   ========================================================================== */
(function (g) {
  'use strict';

  const LEX = {};        // alias -> "tok tok"
  const PHR = {};        // phrase -> "tok tok"
  const CANON = {};      // "tok tok" -> canonical English
  const PCANON = {};
  const GROUPS = [];

  const words = (list, seq) => {
    const al = list.split('/').map(s => s.trim()).filter(Boolean);
    GROUPS.push({ canon: al[0], aliases: al, seq, kind: 'word' });
    al.forEach(w => { if (w.indexOf(' ') < 0) LEX[w] = seq; });
    CANON[seq] = al[0];
  };
  const phrase = (canon, seq) => {
    GROUPS.push({ canon, aliases: [canon], seq, kind: 'phrase' });
    PHR[canon] = seq;
    PCANON[seq] = canon;
  };

  words("i/me/my/mine/myself", 'prr-a-flat-normal');
  words("you/your/yours/yourself", 'prr-e-rise-normal');
  words("we/us/our/ours", 'prr-u-flat-normal');
  words("they/them/their/theirs", 'prr-o-flat-normal');
  words("he/him/his", 'none-a-arch-normal');
  words("she/her/hers", 'prr-o-arch-normal');
  words("it/its/this/that", 'm-u-arch-normal');
  words("human/humans/person/people/hooman/hoomans", 'none-o-flat-normal');
  words("cat/cats/kitty/kitten/kittens", 'prr-y-rise-short');
  words("friend/friends/buddy", 'm-e-rise-normal');
  words("family/mom/mother/dad/father/owner/staff", 'prr-a-fall-long');
  words("hello/hi/hey/yo/hiya", 'none-u-rise-normal');
  words("bye/goodbye/farewell", 'prr-a-fall-normal');
  words("please", 'm-a-dip-short');
  words("thanks/thank/thankyou", 'none-o-rise-normal');
  words("sorry", 'prr-u-fall-long');
  words("yes/yeah/yep/yup/sure", 'prr-u-rise-short');
  words("no/nope/nah/nothing/never", 'm-i-fall-long');
  words("maybe/perhaps/possibly", 'prr-e-dip-normal');
  words("welcome/pleased", 'm-o-rise-normal');
  words("excuse/oops/pardon", 'prr-a-rise-normal');
  words("huh/eh", 'prr-o-rise-normal');
  words("um/hmm/erm", 'prr-i-flat-normal');
  words("ugh/yuck/gross/bleh", 'prr-e-fall-normal');
  words("wow/ooh", 'none-u-arch-normal');
  words("oh", 'm-o-flat-normal');
  words("ow/ouch", 'none-e-fall-short');
  words("eek/eeek", 'none-o-rise-short');
  words("meow/mew/meoww", 'prr-a-arch-long');
  words("food/eat/eating/dinner/breakfast/lunch/snack/meal", 'prr-a-rise-long');
  words("treat/treats/yummy/nummy", 'm-o-arch-long');
  words("fish/tuna/salmon/chicken/meat/shrimp", 'm-a-arch-normal');
  words("water/drink/thirsty/milk/cream", 'h-o-rise-short');
  words("hungry/starving/empty/famished", 'm-o-rise-long');
  words("grass/plant/plants/leaves", 'm-o-rise-short');
  words("want/wants/wanna/need/needs", 'prr-u-arch-normal');
  words("more/another/extra", 'none-y-rise-short');
  words("give/bring/fetch/hand", 'h-u-rise-long');
  words("take/steal/borrow/knock", 'none-a-rise-short');
  words("come/here/closer", 'prr-o-rise-short');
  words("go/gone/leave/away", 'm-a-fall-normal');
  words("sit/stay/down/wait", 'prr-i-fall-normal');
  words("up/jump/leap/climb", 'prr-u-rise-long');
  words("out/outside/exit", 'prr-a-dip-normal');
  words("inside/enter/indoors", 'm-o-flat-long');
  words("play/fun/game/games/toy/toys", 'm-a-rise-long');
  words("pet/petting/cuddle/cuddles/snuggle/rub/scratch", 'prr-o-arch-long');
  words("sleep/sleeping/nap/bed/bedtime/tired/sleepy", 'prr-i-fall-long');
  words("night/moon", 'prr-e-fall-short');
  words("wake/wakeup/woke/morning", 'prr-o-rise-long');
  words("look/looks/watch/watching/see/seeing/peek", 'none-a-dip-long');
  words("listen/hear/hears/sound/noise", 'prr-i-arch-normal');
  words("run/running/chase/dash/zoomies", 'prr-a-flat-short');
  words("walk/walking/wander/stroll", 'h-a-dip-normal');
  words("loaf/lie/lay/laying/sploot", 'prr-a-flat-long');
  words("purr/purring/rumble", 'purr');
  words("hiss/hissing/spit/spitting/scream/yell", 'hiss');
  words("bite/biting/chew/gnaw/nibble/kiss", 'prr-y-fall-normal');
  words("lick/licking/groom/clean/wash", 'h-u-dip-normal');
  words("scare/scared/afraid/startle/flee/hide", 'm-a-dip-long');
  words("hunt/hunting/stalk/pounce/catch/caught", 'prr-o-fall-short');
  words("chatter/chattering/chirp/chirping/bird/birds/mouse/mice/bug/bugs/insect/squirrel/fly/flies", 'none-e-flat-short');
  words("talk/say/says/speak/tell/ask/answer", 'prr-o-dip-normal');
  words("know/knows/knew/understand/understands", 'm-o-fall-normal');
  words("think/wonder/guess/feel/feels", 'prr-i-flat-long');
  words("love/loves/adore/adorable/like/likes", 'prr-u-arch-long');
  words("hate/hates/dislike/angry/mad/annoyed/furious/grumpy", 'm-u-fall-short');
  words("help/rescue/save", 'prr-e-arch-short');
  words("try/trying/attempt", 'prr-e-flat-short');
  words("find/found/lost/search/seeking", 'm-a-arch-long');
  words("keep/keeps/hold/holding", 'prr-e-flat-long');
  words("box/carton/basket/bag", 'prr-u-flat-long');
  words("sofa/couch/lap/blanket/pillow/spot/cushion/chair", 'prr-o-flat-long');
  words("door/window/glass/gate/screen", 'prr-i-flat-short');
  words("string/rope/yarn/ribbon/cord/laser/feather/ball", 'h-o-arch-long');
  words("tree/trees/garden/yard/bush/forest", 'prr-u-dip-short');
  words("sun/sunny/warm/heat/summer/daylight", 'prr-a-dip-short');
  words("cold/wet/rain/snow/winter", 'none-o-dip-normal');
  words("house/home/room/apartment/territory", 'prr-y-flat-long');
  words("car/ride/vet/bath/bathroom/nail/cage/carrier", 'prr-y-arch-long');
  words("day/today/tonight", 'prr-i-dip-normal');
  words("tomorrow/later/soon/after", 'm-a-flat-short');
  words("time/now/minute/second", 'm-e-fall-short');
  words("name/called", 'prr-o-arch-short');
  words("thing/stuff/object/anything/something", 'prr-y-flat-short');
  words("the/a/an/some/any", 'prr-u-flat-short');
  words("and/also/plus/with", 'none-u-flat-short');
  words("or/either", 'none-a-flat-short');
  words("but/however/though", 'none-o-flat-short');
  words("if/when/while", 'm-u-flat-short');
  words("to/for/from/toward", 'none-i-flat-long');
  words("of/than/as", 'm-a-arch-short');
  words("on/at/by/near", 'none-i-arch-short');
  words("not/dont/don't/cant/can't/wont/won't/stop/quit/enough", 'prr-y-fall-short');
  words("is/are/am/was/were/be/been/being/do/does/did/can/could/will/would/should/may/might/must/have/has/had", 'prr-a-dip-long');
  words("very/really/so/too/much/quite/such", 'prr-y-dip-short');
  words("good/great/fine/ok/okay/well/nice/happy/glad/healthy", 'prr-i-dip-long');
  words("bad/awful/terrible/worst/naughty/broken/wrong", 'none-a-fall-normal');
  words("big/huge/large/fat/wide/enormous", 'none-a-arch-short');
  words("small/little/tiny/baby/young/lil", 'prr-i-arch-short');
  words("cute/pretty/beautiful/lovely/sweet/soft/fluffy", 'none-o-arch-short');
  words("best/favorite/beloved/purrfect", 'prr-y-arch-short');
  words("hot/hotter/warmth/toasty", 'h-e-dip-short');
  words("freezing/chilly/frozen", 'prr-e-dip-long');
  words("quiet/gentle/calm/peaceful", 'none-e-dip-long');
  words("loud/noisy/crazy/wild/silly/goofy", 'm-o-arch-short');
  words("boring/dull/slow/meh", 'prr-i-dip-short');
  words("strange/weird/odd/funny/confusing", 'none-u-dip-short');
  words("again/repeat/encore", 'prr-a-fall-short');
  words("always/forever/every/everyday", 'prr-u-fall-short');
  words("hurry/quick/fast/emergency", 'm-e-arch-short');

  /* --------------------------------------------------------------- numbers */
  // n -> n repeats of the counting meow ("zero" gets a sound of its own).
  const COUNT = 'none-o-fall-short';
  GROUPS.push({ canon: 'zero', aliases: ['zero'], seq: 'prr-u-fall-normal', kind: 'number' });
  LEX.zero = 'prr-u-fall-normal'; CANON['prr-u-fall-normal'] = 'zero';
  ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'].forEach((w, idx) => {
    const seq = Array(idx + 1).fill(COUNT).join(' ');
    GROUPS.push({ canon: w, aliases: [w], seq, kind: 'number' });
    LEX[w] = seq; CANON[seq] = w;
  });

  /* ---------------------------------------------------- phrase readings */
  phrase("i love you", 'prr-a-flat-normal prr-u-arch-long prr-e-rise-normal');
  phrase("i love you so much", 'prr-a-flat-normal prr-u-arch-long prr-e-rise-normal prr-y-dip-short prr-y-dip-short');
  phrase("love you", 'prr-u-arch-long prr-e-rise-normal');
  phrase("pet me", 'prr-o-arch-long prr-a-flat-normal');
  phrase("come here", 'prr-o-rise-short prr-o-rise-short');
  phrase("good cat", 'prr-i-dip-long prr-y-rise-short');
  phrase("bad cat", 'none-a-fall-normal prr-y-rise-short');
  phrase("good morning", 'prr-i-dip-long prr-o-rise-long');
  phrase("good night", 'prr-i-dip-long prr-e-fall-short');
  phrase("thank you", 'none-o-rise-normal prr-e-rise-normal');
  phrase("do you want", 'prr-a-dip-long prr-e-rise-normal prr-u-arch-normal');
  phrase("are you hungry", 'prr-a-dip-long prr-e-rise-normal m-o-rise-long');
  phrase("you are", 'prr-e-rise-normal prr-a-dip-long');
  phrase("i am", 'prr-a-flat-normal prr-a-dip-long');
  phrase("i am sorry", 'prr-a-flat-normal prr-a-dip-long prr-u-fall-long');
  phrase("excuse me", 'prr-a-rise-normal prr-a-flat-normal');
  phrase("the best cat", 'prr-u-flat-short prr-y-arch-short prr-y-rise-short');
  phrase("i want", 'prr-a-flat-normal prr-u-arch-normal');
  phrase("i think", 'prr-a-flat-normal prr-i-flat-long');
  phrase("can i", 'prr-a-dip-long prr-a-flat-normal');

  g.MEOW_LEXICON = LEX;
  g.MEOW_PHRASES = PHR;
  g.MEOW_CANON = { CANON, PCANON };
  g.MEOW_GROUPS = GROUPS;
  g.MEOW_COUNT_TOKEN = COUNT;
})(typeof globalThis !== 'undefined' ? globalThis : window);
